from prob13 import findNthOccurence, occurenceNum

def lastFirst(lastCol, i):
    #first column is sorted input
    firstCol = ''.join(sorted(lastCol))
    toFind = transform[i]
    #find the "number letter" it is
    occurence = occurenceNum(lastCol, lastCol[i], i)

    location = findNthOccurence(firstCol, toFind, occurence)

    return location

if __name__ == '__main__':
    transform = "TTTTCTTATCATGATTATAGTAACATTAACGGAGGTCTTCAAAATTCGCAGACGGTCCTCCCGGGGGTTTTTTGGGGGGGAGCTTCTCGCCTCGTTACAAAAAAGGTAAGTACGACCCGCGCTCTACTGTCAAAAAAGAAACCATTTGTACACATGCGCGTCATGAACAACCTGTGATACAGATTTTAATAAATTCCGTAAAATTATTAGTGCCACCATCACGACCGGATAGTACGACCATTGACAGGCTAATTGCTTCTCAATACCTTGATGGGCCGTCCTAGAGGATGCCCCAGCCGCCCCCCAATGTCCGAAGGACGTATGAAACTGGACTTCTGATGCCAAGTTCGAAGCCTCCGGAGAGAACCGTCAAGGTGTCGCTTAAAGGGCTTACAACCCTAGGGCACTCATCACGGTTCGAGTAAGTCTGCCTAGATAGCGCTACCTTCCACACCTGAAGTCAACCACCTCATTGGTATTACTCTTATCTAGAGGTCCCAACTGCGGTGCCAGACCAGGTGTGAAGTAACCGCATTACTACATACTCAACAAATCTTTGGAGGTCGTATTACAAGTTGCGGTCTTCAATTGTTGACTTAATATGCTGTTGGATCGATCAAACATCTGCGACACGCCGACAACCGCGGACCATCCGGGGATGGGGAAATTTCGAGTCGAATCAAATGTGCAGTCTCTGAGGCCGGTCTGTAGCGTACCAACCGCACCCATGTCCAAGGCCGTTAACAATTAATCTGGTCTCATATGGGTTCAGGCCGGCTGAATCGCAGATATCCGCAGGCATACGACAGTTTCCACGCGAATACTTT$"
    print(lastFirst(transform, 131))
